apiVersion: v1
kind: Service
metadata:
  name: bbk-cw-service
  labels:
    app: bbk-cw-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: bbk24cw
  sessionAffinity: None